# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    upload_image_dir: '%kernel.project_dir%/public/uploads/text_image'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    image_optimizer_adapter:
        class: App\ImageOptimizer\ImageOptimizerAdapter

    image_saver:
        class: App\ImageHandlingStrategy\ImageSavingWithCompressStrategy
        arguments: ['%upload_image_dir%', '@image_optimizer_adapter']

    image_service:
        class: App\Service\ImageService
        arguments: ['@image_saver']

    App\Controller\UploadImageController:
        arguments: ['@image_service']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
